default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'hungcom1789'
  host: localhost

development:
  <<: *default
  database: rails

test:
  <<: *default
  database: rails
