default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("USERNAME") %>
  password: <%= ENV.fetch("PASSWORD") %>
  host: <%= ENV.fetch("HOST") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>
